version: "3.9"
services:
  # Frontend service      
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    # If the service should start after another service
    # depends_on:
    #  - backend-server

  # Example how to add a backend service
  # backend-server:
  #   build:
  #     context: .
  #     dockerfile: ./backend/Dockerfile

